
spring:
  application:
    name: leaf-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: leaf_api
            uri: http://localhost:8081
            predicates:
              - Path=/player/**
      globalcors: # 全局跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations: # 对应的路由前缀和跨域配置
          '[/*]': # 匹配所有路由
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8000"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: # 允许在请求中携带的头信息
              - "*"
            allowCredentials: true # 是否允许携带cookie
            maxAge: 3600000


server:
  port: 8010


dubbo:
  application:
    name: dubbo
    qos-port: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-register
    address: nacos://localhost:8848

